export function throwError (): void {
  throw Error('this is an error')
}
